import type { GameEvent, TimelineRange, Category } from "./game-types";

export const GAME_EVENTS: GameEvent[] = [
  // HISTORY events
  {
    id: "hist-001",
    title: "Construction of the Great Pyramid of Giza",
    description: "The largest of the Egyptian pyramids was built as a tomb for Pharaoh Khufu",
    category: "HISTORY",
    correctRange: 0,
  },
  {
    id: "hist-002",
    title: "Fall of the Roman Empire",
    description: "The Western Roman Empire officially came to an end",
    category: "HISTORY",
    correctRange: 1,
  },
  {
    id: "hist-003",
    title: "The Crusades Begin",
    description: "Pope Urban II called for the First Crusade at the Council of Clermont",
    category: "HISTORY",
    correctRange: 3,
  },
  {
    id: "hist-004",
    title: "Columbus Reaches the Americas",
    description: "Christopher Columbus made his first voyage across the Atlantic Ocean",
    category: "HISTORY",
    correctRange: 4,
  },
  {
    id: "hist-005",
    title: "French Revolution",
    description: "The storming of the Bastille marked the beginning of the French Revolution",
    category: "HISTORY",
    correctRange: 5,
  },
  {
    id: "hist-006",
    title: "American Civil War",
    description: "The conflict between the Union and the Confederacy tore America apart",
    category: "HISTORY",
    correctRange: 6,
  },
  {
    id: "hist-007",
    title: "World War I",
    description: "The Great War began, eventually involving most of the world's great powers",
    category: "HISTORY",
    correctRange: 7,
  },
  {
    id: "hist-008",
    title: "Berlin Wall Falls",
    description: "The wall dividing East and West Berlin was torn down",
    category: "HISTORY",
    correctRange: 8,
  },
  {
    id: "hist-009",
    title: "9/11 Attacks",
    description: "Terrorist attacks on the World Trade Center changed the world",
    category: "HISTORY",
    correctRange: 9,
  },
  {
    id: "hist-010",
    title: "Viking Age Begins",
    description: "Norse seafarers began their expansion across Europe",
    category: "HISTORY",
    correctRange: 2,
  },
  {
    id: "hist-011",
    title: "Code of Hammurabi",
    description: "One of the earliest written legal codes was compiled in Babylon",
    category: "HISTORY",
    correctRange: 0,
  },
  {
    id: "hist-012",
    title: "Founding of Rome",
    description: "Legendary founding of the city of Rome",
    category: "HISTORY",
    correctRange: 0,
  },
  {
    id: "hist-013",
    title: "Birth of the Buddha",
    description: "Siddhartha Gautama was born in Lumbini",
    category: "HISTORY",
    correctRange: 0,
  },
  {
    id: "hist-014",
    title: "Han Dynasty Begins",
    description: "The Han dynasty established long-term rule in China",
    category: "HISTORY",
    correctRange: 1,
  },
  {
    id: "hist-015",
    title: "Pax Romana",
    description: "A long period of Roman peace and stability begins",
    category: "HISTORY",
    correctRange: 1,
  },
  {
    id: "hist-016",
    title: "Constantine Embraces Christianity",
    description: "The Roman emperor converted after the Battle of Milvian Bridge",
    category: "HISTORY",
    correctRange: 1,
  },
  {
    id: "hist-017",
    title: "Magna Carta Signed",
    description: "English nobles forced King John to accept limits on royal power",
    category: "HISTORY",
    correctRange: 3,
  },
  {
    id: "hist-018",
    title: "Black Death in Europe",
    description: "A devastating plague swept across Europe",
    category: "HISTORY",
    correctRange: 3,
  },
  {
    id: "hist-019",
    title: "Fall of Constantinople",
    description: "The Ottoman Empire captured the Byzantine capital",
    category: "HISTORY",
    correctRange: 3,
  },
  {
    id: "hist-020",
    title: "Protestant Reformation",
    description: "Martin Luther challenged the Catholic Church",
    category: "HISTORY",
    correctRange: 4,
  },
  {
    id: "hist-021",
    title: "Spanish Armada Defeated",
    description: "England repelled the Spanish Armada",
    category: "HISTORY",
    correctRange: 4,
  },
  {
    id: "hist-022",
    title: "English Civil War",
    description: "Parliament and the monarchy went to war",
    category: "HISTORY",
    correctRange: 4,
  },
  {
    id: "hist-023",
    title: "Glorious Revolution",
    description: "A bloodless coup established constitutional monarchy in England",
    category: "HISTORY",
    correctRange: 4,
  },
  {
    id: "hist-024",
    title: "American Declaration of Independence",
    description: "The thirteen colonies declared independence from Britain",
    category: "HISTORY",
    correctRange: 5,
  },
  {
    id: "hist-025",
    title: "French Revolution Ends",
    description: "The French Revolution closed with Napoleon’s rise",
    category: "HISTORY",
    correctRange: 5,
  },
  {
    id: "hist-026",
    title: "Napoleon Crowned Emperor",
    description: "Napoleon Bonaparte became Emperor of France",
    category: "HISTORY",
    correctRange: 6,
  },
  {
    id: "hist-027",
    title: "Abolition of Slavery in Britain",
    description: "The Slavery Abolition Act took effect",
    category: "HISTORY",
    correctRange: 6,
  },
  {
    id: "hist-028",
    title: "Meiji Restoration",
    description: "Japan began rapid modernization under imperial rule",
    category: "HISTORY",
    correctRange: 6,
  },
  {
    id: "hist-029",
    title: "First Modern Olympics",
    description: "The Olympic Games were revived in Athens",
    category: "HISTORY",
    correctRange: 6,
  },
  {
    id: "hist-030",
    title: "Russian Revolution",
    description: "The Bolsheviks seized power in Russia",
    category: "HISTORY",
    correctRange: 7,
  },
  {
    id: "hist-031",
    title: "Great Depression Begins",
    description: "The global economic crisis started with a stock market crash",
    category: "HISTORY",
    correctRange: 7,
  },
  {
    id: "hist-032",
    title: "United Nations Founded",
    description: "The UN was established after World War II",
    category: "HISTORY",
    correctRange: 7,
  },
  {
    id: "hist-033",
    title: "Indian Independence",
    description: "India gained independence from British rule",
    category: "HISTORY",
    correctRange: 7,
  },
  {
    id: "hist-034",
    title: "Civil Rights Act (US)",
    description: "Landmark legislation outlawed segregation and discrimination",
    category: "HISTORY",
    correctRange: 8,
  },
  {
    id: "hist-035",
    title: "Berlin Wall Built",
    description: "East and West Berlin were divided by a concrete barrier",
    category: "HISTORY",
    correctRange: 8,
  },

  // SCI_TECH events
  {
    id: "tech-001",
    title: "Invention of the Wheel",
    description: "One of humanity's most important inventions revolutionized transportation",
    category: "SCI_TECH",
    correctRange: 0,
  },
  {
    id: "tech-002",
    title: "Gutenberg Printing Press",
    description: "Johannes Gutenberg invented the movable type printing press",
    category: "SCI_TECH",
    correctRange: 4,
  },
  {
    id: "tech-003",
    title: "Newton's Principia Published",
    description: "Isaac Newton published his laws of motion and universal gravitation",
    category: "SCI_TECH",
    correctRange: 5,
  },
  {
    id: "tech-004",
    title: "First Steam Engine",
    description: "James Watt improved the steam engine, powering the Industrial Revolution",
    category: "SCI_TECH",
    correctRange: 5,
  },
  {
    id: "tech-005",
    title: "Telephone Invented",
    description: "Alexander Graham Bell patented the telephone",
    category: "SCI_TECH",
    correctRange: 6,
  },
  {
    id: "tech-006",
    title: "First Airplane Flight",
    description: "The Wright Brothers achieved the first powered flight at Kitty Hawk",
    category: "SCI_TECH",
    correctRange: 7,
  },
  {
    id: "tech-007",
    title: "First Computer (ENIAC)",
    description: "The first general-purpose electronic computer was completed",
    category: "SCI_TECH",
    correctRange: 7,
  },
  {
    id: "tech-008",
    title: "Moon Landing",
    description: "Neil Armstrong became the first human to walk on the Moon",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-009",
    title: "World Wide Web Created",
    description: "Tim Berners-Lee invented the World Wide Web",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-010",
    title: "iPhone Released",
    description: "Apple released the first iPhone, revolutionizing smartphones",
    category: "SCI_TECH",
    correctRange: 9,
  },
  {
    id: "tech-011",
    title: "Paper Invented",
    description: "Papermaking was developed during the Han dynasty",
    category: "SCI_TECH",
    correctRange: 1,
  },
  {
    id: "tech-012",
    title: "Gunpowder Invented",
    description: "Chinese alchemists created an explosive mixture",
    category: "SCI_TECH",
    correctRange: 2,
  },
  {
    id: "tech-013",
    title: "Magnetic Compass Used",
    description: "Navigators began using the compass for direction",
    category: "SCI_TECH",
    correctRange: 2,
  },
  {
    id: "tech-014",
    title: "Astrolabe Widely Adopted",
    description: "The astrolabe became essential for navigation and astronomy",
    category: "SCI_TECH",
    correctRange: 2,
  },
  {
    id: "tech-015",
    title: "Mechanical Clock Developed",
    description: "Early mechanical clocks appeared in European towns",
    category: "SCI_TECH",
    correctRange: 3,
  },
  {
    id: "tech-016",
    title: "Microscope Invented",
    description: "The first compound microscopes were developed in Europe",
    category: "SCI_TECH",
    correctRange: 4,
  },
  {
    id: "tech-017",
    title: "Galileo Uses Telescope",
    description: "Galileo made astronomical discoveries with a telescope",
    category: "SCI_TECH",
    correctRange: 4,
  },
  {
    id: "tech-018",
    title: "Smallpox Vaccination",
    description: "Edward Jenner pioneered vaccination against smallpox",
    category: "SCI_TECH",
    correctRange: 5,
  },
  {
    id: "tech-019",
    title: "Electric Telegraph",
    description: "Long-distance communication by telegraph was demonstrated",
    category: "SCI_TECH",
    correctRange: 6,
  },
  {
    id: "tech-020",
    title: "Light Bulb Patented",
    description: "Edison’s incandescent bulb brought electric lighting",
    category: "SCI_TECH",
    correctRange: 6,
  },
  {
    id: "tech-021",
    title: "X-rays Discovered",
    description: "Wilhelm Röntgen discovered X-rays",
    category: "SCI_TECH",
    correctRange: 6,
  },
  {
    id: "tech-022",
    title: "First Powered Submarine",
    description: "The modern submarine became a reality",
    category: "SCI_TECH",
    correctRange: 6,
  },
  {
    id: "tech-023",
    title: "Penicillin Discovered",
    description: "Alexander Fleming discovered the antibiotic penicillin",
    category: "SCI_TECH",
    correctRange: 7,
  },
  {
    id: "tech-024",
    title: "First Television Broadcast",
    description: "Regular television broadcasts began",
    category: "SCI_TECH",
    correctRange: 7,
  },
  {
    id: "tech-025",
    title: "Transistor Invented",
    description: "The transistor launched a new era of electronics",
    category: "SCI_TECH",
    correctRange: 7,
  },
  {
    id: "tech-026",
    title: "DNA Double Helix",
    description: "Watson and Crick described DNA’s structure",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-027",
    title: "Sputnik Launched",
    description: "The first artificial satellite entered orbit",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-028",
    title: "ARPANET Goes Live",
    description: "The predecessor to the internet connected its first nodes",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-029",
    title: "First Email Sent",
    description: "Ray Tomlinson sent the first network email",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-030",
    title: "IBM PC Released",
    description: "The IBM PC helped standardize personal computers",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-031",
    title: "Hubble Space Telescope",
    description: "Hubble was launched to observe deep space",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-032",
    title: "Dolly the Sheep Cloned",
    description: "The first cloned mammal was born",
    category: "SCI_TECH",
    correctRange: 8,
  },
  {
    id: "tech-033",
    title: "Human Genome Project Completed",
    description: "Scientists mapped the human genome",
    category: "SCI_TECH",
    correctRange: 9,
  },
  {
    id: "tech-034",
    title: "CRISPR Gene Editing",
    description: "CRISPR became a powerful gene-editing tool",
    category: "SCI_TECH",
    correctRange: 9,
  },
  {
    id: "tech-035",
    title: "First Private Mars Probe",
    description: "Private companies sent probes toward Mars",
    category: "SCI_TECH",
    correctRange: 9,
  },

  // CULTURE events
  {
    id: "cult-001",
    title: "Mona Lisa Painted",
    description: "Leonardo da Vinci created his famous masterpiece",
    category: "CULTURE",
    correctRange: 4,
  },
  {
    id: "cult-002",
    title: "Shakespeare's Hamlet",
    description: "William Shakespeare wrote one of his most famous tragedies",
    category: "CULTURE",
    correctRange: 4,
  },
  {
    id: "cult-003",
    title: "Beethoven's 9th Symphony",
    description: "Ludwig van Beethoven premiered his final complete symphony",
    category: "CULTURE",
    correctRange: 6,
  },
  {
    id: "cult-004",
    title: "First Motion Picture",
    description: "The Lumière Brothers held the first public film screening",
    category: "CULTURE",
    correctRange: 6,
  },
  {
    id: "cult-005",
    title: "Jazz Age Begins",
    description: "Jazz music exploded in popularity during the Roaring Twenties",
    category: "CULTURE",
    correctRange: 7,
  },
  {
    id: "cult-006",
    title: "Beatles' British Invasion",
    description: "The Beatles appeared on The Ed Sullivan Show, taking America by storm",
    category: "CULTURE",
    correctRange: 8,
  },
  {
    id: "cult-007",
    title: "First Video Game Console",
    description: "The Magnavox Odyssey became the first home video game console",
    category: "CULTURE",
    correctRange: 8,
  },
  {
    id: "cult-008",
    title: "Harry Potter Published",
    description: "J.K. Rowling published the first Harry Potter book",
    category: "CULTURE",
    correctRange: 8,
  },
  {
    id: "cult-009",
    title: "YouTube Founded",
    description: "The video-sharing platform that changed media was founded",
    category: "CULTURE",
    correctRange: 9,
  },
  {
    id: "cult-010",
    title: "TikTok Goes Global",
    description: "The short-form video app became a worldwide phenomenon",
    category: "CULTURE",
    correctRange: 9,
  },
  {
    id: "cult-011",
    title: "Ancient Olympic Games",
    description: "The original Olympic Games were held at Olympia",
    category: "CULTURE",
    correctRange: 0,
  },
  {
    id: "cult-012",
    title: "Mahabharata Compiled",
    description: "The epic was compiled and expanded in ancient India",
    category: "CULTURE",
    correctRange: 0,
  },
  {
    id: "cult-013",
    title: "Tao Te Ching Written",
    description: "A foundational Taoist text was composed in China",
    category: "CULTURE",
    correctRange: 0,
  },
  {
    id: "cult-014",
    title: "Library of Alexandria Founded",
    description: "A great center of learning was established in Egypt",
    category: "CULTURE",
    correctRange: 1,
  },
  {
    id: "cult-015",
    title: "Colosseum Opens",
    description: "Rome opened its massive amphitheater to the public",
    category: "CULTURE",
    correctRange: 1,
  },
  {
    id: "cult-016",
    title: "Hagia Sophia Completed",
    description: "The monumental church in Constantinople was completed",
    category: "CULTURE",
    correctRange: 1,
  },
  {
    id: "cult-017",
    title: "Beowulf Written",
    description: "The Old English epic poem was composed",
    category: "CULTURE",
    correctRange: 2,
  },
  {
    id: "cult-018",
    title: "Notre-Dame Construction Begins",
    description: "Work began on the famous Paris cathedral",
    category: "CULTURE",
    correctRange: 3,
  },
  {
    id: "cult-019",
    title: "Sistine Chapel Ceiling",
    description: "Michelangelo completed the ceiling paintings",
    category: "CULTURE",
    correctRange: 4,
  },
  {
    id: "cult-020",
    title: "Don Quixote Published",
    description: "Miguel de Cervantes published his famous novel",
    category: "CULTURE",
    correctRange: 4,
  },
  {
    id: "cult-021",
    title: "First Newspaper in Europe",
    description: "Printed newspapers began circulating regularly",
    category: "CULTURE",
    correctRange: 4,
  },
  {
    id: "cult-022",
    title: "Ballet at the French Court",
    description: "Ballet flourished as a royal court entertainment",
    category: "CULTURE",
    correctRange: 4,
  },
  {
    id: "cult-023",
    title: "Pamela Published",
    description: "Samuel Richardson’s novel helped shape modern fiction",
    category: "CULTURE",
    correctRange: 5,
  },
  {
    id: "cult-024",
    title: "The Magic Flute Premieres",
    description: "Mozart’s opera premiered in Vienna",
    category: "CULTURE",
    correctRange: 5,
  },
  {
    id: "cult-025",
    title: "Photography Introduced",
    description: "The daguerreotype made images reproducible",
    category: "CULTURE",
    correctRange: 6,
  },
  {
    id: "cult-026",
    title: "First Impressionist Exhibition",
    description: "Impressionist painters debuted their work in Paris",
    category: "CULTURE",
    correctRange: 6,
  },
  {
    id: "cult-027",
    title: "Public Radio Broadcasts Begin",
    description: "Regular radio programming reached mass audiences",
    category: "CULTURE",
    correctRange: 7,
  },
  {
    id: "cult-028",
    title: "Jazz Recordings Popularized",
    description: "Jazz music spread through recordings and radio",
    category: "CULTURE",
    correctRange: 7,
  },
  {
    id: "cult-029",
    title: "Snow White Released",
    description: "Disney released the first feature-length animated film",
    category: "CULTURE",
    correctRange: 7,
  },
  {
    id: "cult-030",
    title: "First TV Sitcom Hit",
    description: "Television sitcoms became a household staple",
    category: "CULTURE",
    correctRange: 8,
  },
  {
    id: "cult-031",
    title: "Woodstock Festival",
    description: "Iconic music festival drew hundreds of thousands",
    category: "CULTURE",
    correctRange: 8,
  },
  {
    id: "cult-032",
    title: "Star Wars Released",
    description: "The sci-fi film launched a global franchise",
    category: "CULTURE",
    correctRange: 8,
  },
  {
    id: "cult-033",
    title: "Hip-Hop Emerges",
    description: "Hip-hop culture rose in New York City",
    category: "CULTURE",
    correctRange: 8,
  },
  {
    id: "cult-034",
    title: "First Harry Potter Film",
    description: "The wizarding world arrived in cinemas",
    category: "CULTURE",
    correctRange: 9,
  },
  {
    id: "cult-035",
    title: "Streaming Era Takes Off",
    description: "On-demand streaming reshaped entertainment",
    category: "CULTURE",
    correctRange: 9,
  },

  // TRAVEL events
  {
    id: "trav-001",
    title: "Silk Road Established",
    description: "Ancient trade routes connected East and West",
    category: "TRAVEL",
    correctRange: 1,
  },
  {
    id: "trav-002",
    title: "Marco Polo's Journey",
    description: "The Venetian explorer traveled to China and back",
    category: "TRAVEL",
    correctRange: 3,
  },
  {
    id: "trav-003",
    title: "Magellan's Circumnavigation",
    description: "The first expedition to sail around the entire Earth",
    category: "TRAVEL",
    correctRange: 4,
  },
  {
    id: "trav-004",
    title: "First Hot Air Balloon",
    description: "The Montgolfier Brothers demonstrated the first hot air balloon",
    category: "TRAVEL",
    correctRange: 5,
  },
  {
    id: "trav-005",
    title: "Transcontinental Railroad",
    description: "The first railroad connecting the US East and West coasts was completed",
    category: "TRAVEL",
    correctRange: 6,
  },
  {
    id: "trav-006",
    title: "Titanic Sinks",
    description: "The 'unsinkable' ship hit an iceberg on its maiden voyage",
    category: "TRAVEL",
    correctRange: 7,
  },
  {
    id: "trav-007",
    title: "First Commercial Airline",
    description: "The first scheduled commercial airline service began",
    category: "TRAVEL",
    correctRange: 7,
  },
  {
    id: "trav-008",
    title: "Concorde's First Flight",
    description: "The supersonic passenger airliner took its maiden voyage",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-009",
    title: "International Space Station",
    description: "The first module of the ISS was launched into orbit",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-010",
    title: "SpaceX Crew Dragon",
    description: "The first private spacecraft to carry astronauts to the ISS",
    category: "TRAVEL",
    correctRange: 9,
  },
  {
    id: "trav-011",
    title: "Polynesians Reach Hawaii",
    description: "Skilled navigators settled the Hawaiian Islands",
    category: "TRAVEL",
    correctRange: 2,
  },
  {
    id: "trav-012",
    title: "Vikings Reach Vinland",
    description: "Norse explorers landed in North America",
    category: "TRAVEL",
    correctRange: 2,
  },
  {
    id: "trav-013",
    title: "Zheng He’s Treasure Voyages",
    description: "A massive Chinese fleet sailed across the Indian Ocean",
    category: "TRAVEL",
    correctRange: 3,
  },
  {
    id: "trav-014",
    title: "Inca Road Network",
    description: "The Inca expanded a vast road system across the Andes",
    category: "TRAVEL",
    correctRange: 3,
  },
  {
    id: "trav-015",
    title: "Prince Henry’s Voyages",
    description: "Portuguese expeditions mapped West Africa’s coast",
    category: "TRAVEL",
    correctRange: 3,
  },
  {
    id: "trav-016",
    title: "Cape of Good Hope Reached",
    description: "Portuguese sailors rounded Africa’s southern tip",
    category: "TRAVEL",
    correctRange: 3,
  },
  {
    id: "trav-017",
    title: "First Transatlantic Cable",
    description: "A telegraph cable linked Europe and North America",
    category: "TRAVEL",
    correctRange: 6,
  },
  {
    id: "trav-018",
    title: "Suez Canal Opens",
    description: "A new sea route connected the Mediterranean to the Red Sea",
    category: "TRAVEL",
    correctRange: 6,
  },
  {
    id: "trav-019",
    title: "Orient Express Begins Service",
    description: "Luxury rail travel connected Paris and Istanbul",
    category: "TRAVEL",
    correctRange: 6,
  },
  {
    id: "trav-020",
    title: "First Around-the-World Flight",
    description: "Aircraft completed the first circumnavigation by air",
    category: "TRAVEL",
    correctRange: 7,
  },
  {
    id: "trav-021",
    title: "Route 66 Established",
    description: "The iconic U.S. highway linked Chicago and Los Angeles",
    category: "TRAVEL",
    correctRange: 7,
  },
  {
    id: "trav-022",
    title: "Lindbergh Crosses the Atlantic",
    description: "A solo nonstop flight crossed the Atlantic Ocean",
    category: "TRAVEL",
    correctRange: 7,
  },
  {
    id: "trav-023",
    title: "First Passenger Jet Service",
    description: "Jet airliners entered commercial service",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-024",
    title: "Shinkansen Launch",
    description: "Japan opened the first high-speed rail line",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-025",
    title: "Apollo 8 Orbits the Moon",
    description: "Humans first orbited the Moon during Apollo 8",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-026",
    title: "Concorde Enters Service",
    description: "Supersonic passenger flights began",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-027",
    title: "Channel Tunnel Opens",
    description: "A rail tunnel linked Britain and France",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-028",
    title: "Eurostar Service Begins",
    description: "High-speed rail connected London with Paris and Brussels",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-029",
    title: "GPS Fully Operational",
    description: "Global Positioning System reached full capability",
    category: "TRAVEL",
    correctRange: 8,
  },
  {
    id: "trav-030",
    title: "SpaceShipOne Wins X Prize",
    description: "Private spaceflight achieved a major milestone",
    category: "TRAVEL",
    correctRange: 9,
  },
  {
    id: "trav-031",
    title: "Airbus A380 Enters Service",
    description: "The world’s largest passenger plane began flights",
    category: "TRAVEL",
    correctRange: 9,
  },
  {
    id: "trav-032",
    title: "Commercial Space Tourism",
    description: "Paying passengers reached space on commercial flights",
    category: "TRAVEL",
    correctRange: 9,
  },
  {
    id: "trav-033",
    title: "China’s High-Speed Rail Boom",
    description: "Rapid expansion created the world’s largest HSR network",
    category: "TRAVEL",
    correctRange: 9,
  },
  {
    id: "trav-034",
    title: "Solar Impulse Circumnavigation",
    description: "A solar-powered plane flew around the world",
    category: "TRAVEL",
    correctRange: 9,
  },
  {
    id: "trav-035",
    title: "Reusable Rockets Land",
    description: "Reusable boosters landed safely for relaunch",
    category: "TRAVEL",
    correctRange: 9,
  },
];

// Get events by category
export function getEventsByCategory(category: Category): GameEvent[] {
  if (category === "RANDOM") {
    return GAME_EVENTS;
  }
  return GAME_EVENTS.filter((event) => event.category === category);
}

// Get random event
export function getRandomEvent(category?: Category, excludeIds?: string[]): GameEvent {
  let events = category && category !== "RANDOM" 
    ? getEventsByCategory(category) 
    : GAME_EVENTS;
  
  if (excludeIds && excludeIds.length > 0) {
    events = events.filter((e) => !excludeIds.includes(e.id));
  }
  
  if (events.length === 0) {
    events = GAME_EVENTS;
  }
  
  return events[Math.floor(Math.random() * events.length)];
}

// Get event by ID (server-side only - includes correctRange)
export function getEventById(id: string): GameEvent | undefined {
  return GAME_EVENTS.find((event) => event.id === id);
}

// Get event for client (excludes correctRange)
export function getEventForClient(id: string): Omit<GameEvent, "correctRange"> | undefined {
  const event = getEventById(id);
  if (!event) return undefined;
  
  const { correctRange, ...clientEvent } = event;
  return clientEvent;
}

// Generate hint for SUPPORT rounds
export function generateHint(correctRange: TimelineRange): string {
  const minHint = Math.max(0, correctRange - 1);
  const maxHint = Math.min(9, correctRange + 1);
  return `The answer is somewhere between ${minHint} and ${maxHint}`;
}
